[package]
name = "clock-cli"
version = "0.0.1"
authors = ["Tianyi Shi <ShiTianyi2001@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cursive = "0.15.0"
#clap = "2.33.3"
chrono = "0.4.15"

[[bin]]
name = "clock"
path = "src/main.rs"